### ISSUE TITLE
No need for a shell script to launch the program from the command line

### ISSUE THREAD

**Issue by probonopd** [iboyperson/aim#1]
> Aim is designed to download the Appimage to a centralized directory and then create a shell script to launch the program from the command line (if the bin folder containing the scripts is added to the path).

The latter is not needed: just put the AppImage into a directory that is on the `$PATH` - no need for a shell script...

**Comment by iboyperson** [comment]
While adding the files to the path directly is indeed possible I personally find the long and clunky file name unappealing. That is why I added the creation of the bin file with the shortened name.

**Comment by probonopd** [comment]
> While adding the files to the path directly is indeed possible I personally find the long and clunky file name unappealing. 

Why don't you just rename them then? (No need for the `.AppImage` suffix either)

**Comment by iboyperson** [comment]
That is a good idea. Strangely the thought had simply never occured to me. I will impliment this as soon as I can

**Comment by iboyperson** [comment]
Just pushed commit implimenting this. Closing the issue.
